//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MCDraw.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_MCDRAW_STATUS_BAR            101
#define IDR_MAINFRAME                   128
#define IDR_MCDRAWTYPE                  129
#define IDR_DRAWTOOLS                   131
#define IDR_COLORS                      136
#define IDR_TEXT                        138
#define IDB_LINE1A                      141
#define IDB_LINE1D                      142
#define IDD_OPT_SHOW                    142
#define IDB_LINE2D                      143
#define IDD_OPT_SIZE                    143
#define IDB_LINE2A                      144
#define IDD_OPT_GRID                    144
#define IDB_LINE5A                      145
#define IDB_LINE5D                      146
#define IDB_LINE6A                      147
#define IDB_LINE6D                      148
#define IDB_NULLA                       149
#define IDB_DOTA                        150
#define IDB_SOLIDA                      151
#define IDB_LINE3A                      152
#define IDB_LINE3D                      153
#define IDB_LINE4A                      154
#define IDB_LINE4D                      155
#define IDB_NULLD                       156
#define IDB_SOLIDD                      157
#define IDB_DOTD                        158
#define IDB_FDIAGONALA                  159
#define IDB_CROSSD                      160
#define IDB_DIAGCROSSA                  161
#define IDB_DIAGCROSSD                  162
#define IDB_BDIAGONALA                  163
#define IDB_BDIAGONALD                  164
#define IDB_VERTICALA                   165
#define IDB_VERTICALD                   166
#define IDB_DASHA                       167
#define IDB_DASHD                       168
#define IDB_DASHDOTA                    169
#define IDB_DASHDOTD                    170
#define IDB_DASHDOTDOTA                 171
#define IDB_DASHDOTDOTD                 172
#define IDB_BSOLIDA                     173
#define IDB_BSOLIDD                     174
#define IDB_BNULLA                      175
#define IDB_BNULLD                      176
#define IDB_FDIAGONALD                  177
#define IDB_CROSSA                      178
#define IDB_HORIZONTALA                 179
#define IDB_HORIZONTALD                 180
#define IDD_DNYATTR                     183
#define IDD_INPUT_D                     184
#define IDD_INPUT_A                     185
#define IDD_SLIDE_H                     186
#define IDD_SLIDE_V                     187
#define IDD_BUTTON_D                    188
#define IDD_BUTTON_A                    189
#define IDD_BUTTON_WND                  190
#define IDD_VALUE_D                     191
#define IDD_VALUE_A                     192
#define IDD_COLOR_D                     193
#define IDD_COLOR_A                     194
#define IDD_COLOR_DA                    195
#define IDD_COLOR_AA                    196
#define IDD_SIZE_H                      197
#define IDD_SIZE_V                      198
#define IDD_FILL_H                      199
#define IDD_FILL_V                      200
#define IDD_POS_H                       201
#define IDD_POS_V                       202
#define IDD_VISIBILITY                  203
#define IDD_BLINK                       204
#define IDD_DIRECTION                   205
#define IDD_ENABLE                      206
#define IDC_CURSOR1                     209
#define IDD_CELLATTR                    210
#define IDD_SELECT                      211
#define IDD_SAVE                        212
#define IDD_REPLACE                     215
#define IDD_TRENDATTR                   219
#define IDB_BITMAP1                     222
#define IDR_POPUP                       223
#define IDC_MM_ANISOTROPIC              1002
#define IDC_MM_TEXT                     1003
#define IDC_PIX_HOR                     1004
#define IDC_PIX_VER                     1005
#define IDC_SHOWGRID                    1006
#define IDC_OPTRANK                     1009
#define IDC_HORGRID                     1015
#define IDC_VERGRID                     1016
#define IDC_LOCKONGRID                  1017
#define IDC_WNDWIDTH                    1018
#define IDC_WNDHEIGHT                   1019
#define IDC_WNDCAPTION                  1020
#define IDC_INPUT_B                     1021
#define IDC_INPUT_D                     1021
#define IDC_INPUT_A                     1022
#define IDC_SLIDE_H                     1023
#define IDC_SLIDE_V                     1024
#define IDC_BUTTON_D                    1025
#define IDC_BUTTON_A                    1026
#define IDC_BUTTON_WND                  1027
#define IDC_PENCOLOR_D                  1028
#define IDC_TAGNAME                     1029
#define IDC_SELTAG                      1030
#define IDC_PENCOLOR_A                  1031
#define IDC_WNDPRM                      1031
#define IDC_BRUSHCOLOR_D                1032
#define IDC_SETPRM                      1032
#define IDC_BRUSHCOLOR_A                1033
#define IDC_RESETPRM                    1033
#define IDC_BOTTOM                      1033
#define IDC_TEXTCOLOR_D                 1034
#define IDC_ONMSG                       1034
#define IDC_HORCEN                      1034
#define IDC_TEXTCOLOR_A                 1035
#define IDC_OFFMSG                      1035
#define IDC_RIGHT                       1035
#define IDC_SIZE_H                      1036
#define IDC_LEFTVAL                     1036
#define IDC_LEFTSLIDE_O                 1036
#define IDC_SIZE_V                      1037
#define IDC_RIGHTVAL                    1037
#define IDC_RIGHTSLIDE_O                1037
#define IDC_POS_H                       1038
#define IDC_RIGHTSET                    1038
#define IDC_RIGHTSLIDE_T                1038
#define IDC_POS_V                       1039
#define IDC_LEFTSET                     1039
#define IDC_LEFTSLIDE_T                 1039
#define IDC_FILL_H                      1040
#define IDC_TOPVAL                      1040
#define IDC_TOPSLIDE_O                  1040
#define IDC_FILL_V                      1041
#define IDC_BOTTOMVAL                   1041
#define IDC_BOTTOMSLIDE_O               1041
#define IDC_VALUE_D                     1042
#define IDC_TOPSET                      1042
#define IDC_TOPSLIDE_T                  1042
#define IDC_VALUE_A                     1043
#define IDC_BOTTOMSET                   1043
#define IDC_BOTTOMSLIDE_T               1043
#define IDC_VISIBLE                     1044
#define IDC_SET                         1044
#define IDC_BLINK                       1045
#define IDC_RESET                       1045
#define IDC_DIRECTION                   1046
#define IDC_NOT                         1046
#define IDC_INC                         1046
#define IDC_DISABLE                     1047
#define IDC_SETONPUSH                   1047
#define IDC_DEC                         1047
#define IDC_RESETONPUSH                 1048
#define IDC_NUM                         1048
#define IDC_UP_LIMIT                    1049
#define IDC_BROWSE                      1049
#define IDC_DOWN_LIMIT                  1050
#define IDC_WNDNAME                     1050
#define IDC_SPLIT3                      1050
#define IDC_POPUP                       1051
#define IDC_SPLIT2                      1051
#define IDC_OVERLAP                     1052
#define IDC_MAXWIDTH_O                  1052
#define IDC_SPLIT1                      1052
#define IDC_MINWIDTH_O                  1053
#define IDC_LEFT                        1054
#define IDC_MAXWIDTH_T                  1055
#define IDC_TEXTCOLOR_DA                1056
#define IDC_MINWIDTH_T                  1056
#define IDC_TEXTCOLOR_AA                1057
#define IDC_MAXHEIGHT_O                 1057
#define IDC_BRUSHCOLOR_DA               1058
#define IDC_MINHEIGHT_O                 1058
#define IDC_BRUSHCOLOR_AA               1059
#define IDC_MAXHEIGHT_T                 1059
#define IDC_PENCOLOR_DA                 1060
#define IDC_MINHEIGHT_T                 1060
#define IDC_PENCOLOR_AA                 1061
#define IDC_VERCEN                      1061
#define IDC_TOP                         1062
#define IDC_LEFTPOS_O                   1063
#define IDC_RIGHTPOS_O                  1064
#define IDC_LEFTPOS_T                   1065
#define IDC_RIGHTPOS_T                  1066
#define IDC_TOPPOS_O                    1067
#define IDC_BOTTOMPOS_O                 1068
#define IDC_TOPPOS_T                    1069
#define IDC_BOTTOMPOS_T                 1070
#define IDC_VISIBALE                    1071
#define IDC_NOT_VISIBLE                 1072
#define IDC_MINCLOCKWISE_O              1072
#define IDC_MAXCLOCKWISE_O              1073
#define IDC_FAST                        1073
#define IDC_MINCLOCKWISE_T              1074
#define IDC_NOMAL                       1074
#define IDC_MAXCLOCKWISE_T              1075
#define IDC_YBIAS                       1076
#define IDC_FORMAT                      1076
#define IDC_SLOW                        1076
#define IDC_XBIAS                       1077
#define IDC_MAXHFILL_O                  1077
#define IDC_MINHFILL_O                  1078
#define IDC_MAXHFILL_T                  1079
#define IDC_MINHFILL_T                  1080
#define IDC_MAXVFILL_O                  1081
#define IDC_MINVFILL_O                  1082
#define IDC_MAXVFILL_T                  1083
#define IDC_MINVFILL_T                  1084
#define IDC_MAXVALUE                    1085
#define IDC_MINVALUE                    1086
#define IDC_COLORON                     1088
#define IDC_COLOROFF                    1089
#define IDC_COLORALARM                  1089
#define IDC_COLORNOMAL                  1090
#define IDC_COLOR3                      1091
#define IDC_COLOR2                      1092
#define IDC_COLOR1                      1093
#define IDC_COLOR0                      1094
#define IDC_PEN1                        1094
#define IDC_SELTAG1                     1094
#define IDC_COLOR4                      1095
#define IDC_SELTAG11                    1095
#define IDC_SPLIT4                      1096
#define IDC_COLORR                      1096
#define IDC_PEN2                        1096
#define IDC_SELTAG2                     1096
#define IDC_COLORH2                     1097
#define IDC_SELTAG12                    1097
#define IDC_COLORH1                     1098
#define IDC_COLORBRUSH                  1098
#define IDC_PEN3                        1098
#define IDC_SELTAG3                     1098
#define IDC_COLORN                      1099
#define IDC_COLORHTEXT                  1099
#define IDC_SELTAG13                    1099
#define IDC_COLORL1                     1100
#define IDC_PEN4                        1100
#define IDC_SELTAG4                     1100
#define IDC_COLORL2                     1101
#define IDC_SELTAG14                    1101
#define IDC_COLORPEN                    1102
#define IDC_PEN5                        1102
#define IDC_SELTAG5                     1102
#define IDC_ENABLE                      1103
#define IDC_BKCOLOR                     1103
#define IDC_GDCOLOR                     1104
#define IDC_CVALUE_D                    1105
#define IDC_PEN6                        1105
#define IDC_SELTAG6                     1105
#define IDC_CPENCOLOR_D                 1106
#define IDC_PEN7                        1106
#define IDC_SELTAG7                     1106
#define IDC_CBRUSHCOLOR_D               1107
#define IDC_PEN8                        1107
#define IDC_SELTAG8                     1107
#define IDC_CTEXTCOLOR_D                1108
#define IDC_PEN9                        1108
#define IDC_SELTAG9                     1108
#define IDC_CSIZE_H                     1109
#define IDC_PEN10                       1109
#define IDC_SELTAG10                    1109
#define IDC_CPOS_H                      1110
#define IDC_SELTAG15                    1110
#define IDC_CFILL_H                     1111
#define IDC_SELTAG16                    1111
#define IDC_CVISIBLE                    1112
#define IDC_SELTAG17                    1112
#define IDC_CVALUE_A                    1113
#define IDC_SELTAG18                    1113
#define IDC_CPENCOLOR_A                 1114
#define IDC_SELTAG19                    1114
#define IDC_CBRUSHCOLOR_A               1115
#define IDC_SELTAG20                    1115
#define IDC_CTEXTCOLOR_A                1116
#define IDC_CSIZE_V                     1117
#define IDC_CPOS_V                      1118
#define IDC_CFILL_V                     1119
#define IDC_CBLINK                      1120
#define IDC_CPENCOLOR_DA                1121
#define IDC_CBRUSHCOLOR_DA              1122
#define IDC_CTEXTCOLOR_DA               1123
#define IDC_CDIRECTION                  1124
#define IDC_CPENCOLOR_AA                1125
#define IDC_CBRUSHCOLOR_AA              1126
#define IDC_CTEXTCOLOR_AA               1127
#define IDC_CENABLE                     1128
#define IDC_CINPUT_D                    1129
#define IDC_CSLIDE_H                    1130
#define IDC_CBUTTON_D                   1131
#define IDC_CINPUT_A                    1132
#define IDC_CSLIDE_V                    1133
#define IDC_CBUTTON_A                   1134
#define IDC_CBUTTON_WND                 1135
#define IDC_TAGS                        1137
#define IDC_TAG                         1138
#define IDC_REPLACE                     1139
#define IDC_NEWTAGS                     1140
#define IDC_OBJECTS                     1140
#define IDC_PREVIEW                     1141
#define IDC_SELECT                      1143
#define IDC_REPLACED                    1150
#define IDC_ORIGINAL                    1151
#define IDC_TAG1                        1153
#define IDC_TAG2                        1154
#define IDC_TAG3                        1155
#define IDC_TAG4                        1156
#define IDC_TAG5                        1157
#define IDC_TAG6                        1158
#define IDC_TAG7                        1159
#define IDC_TAG8                        1160
#define IDC_TAG9                        1161
#define IDC_LENGTH                      1162
#define IDC_TAG10                       1163
#define IDC_CA1                         1164
#define IDC_CA2                         1165
#define IDC_CA3                         1166
#define IDC_CA4                         1167
#define IDC_CA5                         1168
#define IDC_MIN1                        1169
#define IDC_MAX1                        1170
#define IDC_MIN2                        1171
#define IDC_LIST_FORMAT                 1171
#define IDC_MAX2                        1172
#define IDC_COMBO1                      1172
#define IDC_MIN3                        1173
#define IDC_MAX3                        1174
#define IDC_TAG_NAME                    1174
#define IDC_MIN4                        1175
#define IDC_MAX4                        1176
#define IDC_RANK0                       1176
#define IDC_MIN5                        1177
#define IDC_RANK1                       1177
#define IDC_MAX5                        1178
#define IDC_RANK2                       1178
#define IDC_CA6                         1179
#define IDC_RANK3                       1179
#define IDC_MIN6                        1180
#define IDC_RANK4                       1180
#define IDC_MAX6                        1181
#define IDC_RANK5                       1181
#define IDC_CA7                         1182
#define IDC_RANK6                       1182
#define IDC_MIN7                        1183
#define IDC_RANK7                       1183
#define IDC_MAX7                        1184
#define IDC_RANK8                       1184
#define IDC_CA8                         1185
#define IDC_CHECK10                     1185
#define IDC_RANK9                       1185
#define IDC_MIN8                        1186
#define IDC_MAX8                        1187
#define IDC_CA9                         1188
#define IDC_MIN9                        1189
#define IDC_MAX9                        1190
#define IDC_CA10                        1191
#define IDC_MIN10                       1192
#define IDC_MAX10                       1193
#define ID_VIEW_GRID                    32771
#define ID_VIEW_ZOOM_ALL                32775
#define ID_VIEW_ZOOM_1                  32776
#define ID_VIEW_ZOOM_2                  32777
#define ID_VIEW_ZOOM_3                  32778
#define ID_VIEW_ZOOM_4                  32779
#define ID_VIEW_ZOOM_5                  32780
#define ID_DRAW_POINTER                 32781
#define ID_DRAW_LINE                    32782
#define ID_DRAW_ARC                     32783
#define ID_DRAW_POLYLINE                32784
#define ID_DRAW_BENDLINE                32785
#define ID_DRAW_RECTANGLE               32786
#define ID_DRAW_ROUNDRECT               32787
#define ID_DRAW_ELLIPSE                 32788
#define ID_DRAW_POLYGON                 32789
#define ID_DRAW_TEXT                    32790
#define ID_DRAW_BUTTON                  32791
#define ID_DRAW_PICURE                  32792
#define ID_DRAW_LIBCOMP                 32793
#define ID_PEN_COLOR                    32800
#define ID_BRUSH_COLOR                  32801
#define ID_FONT_COLOR                   32802
#define ID_WINDOW_COLOR                 32803
#define ID_COLOR_PEN                    32804
#define ID_COLOR_BRUSH                  32805
#define ID_COLOR_FONT                   32806
#define ID_COLOR_WINDOW                 32807
#define ID_LINE_1                       32808
#define ID_LINE_2                       32809
#define ID_LINE_3                       32810
#define ID_LINE_4                       32811
#define ID_LINE_5                       32812
#define ID_LINE_6                       32813
#define ID_LINE_NULL                    32814
#define ID_LINE_SOLID                   32815
#define ID_LINE_DOT                     32816
#define ID_LINE_DASHDOT                 32817
#define ID_LINE_DASHDOTDOT              32818
#define ID_LINE_DASH                    32819
#define ID_BRUSH_SOLID                  32820
#define ID_BRUSH_NULL                   32821
#define ID_BRUSH_BDIAGONAL              32822
#define ID_BRUSH_CROSS                  32823
#define ID_BRUSH_DIAGCROSS              32824
#define ID_BRUSH_FDIAGONAL              32825
#define ID_BRUSH_HORIZONTAL             32826
#define ID_BRUSH_VERTICAL               32827
#define IDR_FONT_SET                    32828
#define IDR_FONT_BOLD                   32829
#define IDR_FONT_ITALIC                 32830
#define IDR_FONT_UNDERLINE              32831
#define IDR_TEXT_SET                    32832
#define IDR_TEXT_BOLD                   32833
#define IDR_TEXT_ITALIC                 32834
#define IDR_TEXT_UNDERLINE              32835
#define ID_FORMAT_B2F                   32836
#define ID_FORMAT_B2B                   32837
#define ID_FORMAT_A2L                   32839
#define ID_FORMAT_A2C                   32840
#define ID_FORMAT_A2R                   32841
#define ID_FORMAT_A2T                   32842
#define ID_FORMAT_A2M                   32843
#define ID_FORMAT_A2B                   32844
#define ID_FORMAT_A2CM                  32845
#define ID_FORMAT_E2H                   32846
#define ID_FORMAT_E2V                   32847
#define ID_FORMAT_R2W                   32848
#define ID_FORMAT_R2U                   32849
#define ID_FORMAT_F2Z                   32850
#define ID_FORMAT_F2I                   32851
#define ID_FORMAT_S2G                   32852
#define ID_TOOLS_META                   32853
#define ID_TOOLS_MKCELL                 32854
#define ID_TOOLS_UPCELL                 32855
#define ID_TOOLS_GRID                   32856
#define ID_TOOLS_OPTIONS                32858
#define ID_MENUITEID_VIEW_TOOLBAR       32859
#define ID_VIEW_COLOR                   32860
#define ID_VIEW_FONT                    32861
#define ID_VIEW_DRAW                    32862
#define ID_EDIT_DELETE                  32863
#define ID_TOOLS_SAVECELL               32864
#define ID_EDIT_TEXT                    32865
#define ID_DRAW_TREND                   32866
#define ID_TOOLS                        32871
#define ID_COLOR                        32872
#define ID_TOOLS_LOCK                   32873
#define ID_TOOLS_UNLOCK                 32874
#define IDM_SHOW_ALL_ATTRIBS            32875
#define IDD_SELECTALL                   32876
#define IDM_SELECT_PROJECT              32877
#define IDR_PROJECT_START               32878
#define IDR_PROJECT_RUN_CURRENT         32879
#define IDR_PROJECT_START_DB            32880
#define IDR_PROJECT_NAME                32881
#define IDR_PROJECT_RESTART_DB          32882
#define IDR_PROJECT_CONFIG_DB           32883
#define IDR_PROJECT_STOPDB              32884
#define ID_FILE_SAVE_AS_BMP             32885
#define ID_INDICATOR_POS                59142
#define ID_INDICATOR_SIZE               59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        226
#define _APS_NEXT_COMMAND_VALUE         32886
#define _APS_NEXT_CONTROL_VALUE         1195
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
