//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mcview.rc
//
#define IDC_ALARMLIST                   3
#define IDC_ADD                         3
#define IDC_0                           3
#define IDC_ACKALARM                    4
#define IDC_RETURN_WND                  4
#define IDC_DELETE                      4
#define IDC_10                          4
#define IDC_INDEX                       5
#define IDC_PRINT                       5
#define IDC_PREVIOUS                    6
#define IDC_ACK                         6
#define IDC_ABOUT                       6
#define IDC_NEXT                        7
#define IDC_ACKALL                      7
#define IDC_KEY                         8
#define IDC_LOOP                        9
#define IDC_CLR                         17
#define IDC_1                           18
#define IDC_2                           19
#define IDC_3                           20
#define IDC_4                           21
#define IDC_5                           22
#define IDC_6                           24
#define IDC_7                           25
#define IDC_8                           26
#define IDC_9                           27
#define IDC_SUB                         28
#define IDC_DOT                         29
#define IDD_MCVIEW_DIALOG               102
#define IDD_FVIEW_DIALOG                106
#define IDR_MAINFRAME                   128
#define IDD_VIEW                        129
#define IDC_PUSH                        130
#define IDD_POPUP                       131
#define IDD_INPUT_D                     132
#define IDC_UPUSH                       133
#define IDI_NA                          136
#define IDD_INPUT_A                     138
#define IDD_ALARMLIST                   139
#define IDD_TREND_TIME                  140
#define IDD_PASSWORD                    143
#define IDD_ABOUT                       144
#define IDD_MCVIEW_DIALOG_S             148
#define IDD_TRENDCOMPS                  150
#define IDD_DNYTIP                      151
#define IDD_LOOP                        152
#define IDD_SELECT                      154
#define IDD_SYSTEM_NEW                  161
#define IDD_USEREDIT                    162
#define IDD_USERGROUP_EDIT              163
#define IDD_USERGROUPNEW                164
#define IDD_USERNEW                     165
#define IDD_USERMANAGER                 166
#define IDR_USERMANAGER                 167
#define IDD_ALARM_DIALOG                168
#define IDD_QUERYDLG                    169
#define IDD_SELECTKEYNAME_DIALOG        171
#define IDI_ICON_R1                     174
#define IDI_ICON_G2                     175
#define IDI_ICON_G1                     176
#define IDI_ICON_R2                     177
#define IDI_ICON_Y1                     178
#define IDI_ICON_Y2                     179
#define IDI_ICON_W1                     180
#define IDI_ICON1                       181
#define IDI_ICON_W2                     181
#define IDC_SYSTEM                      1000
#define IDC_TIME                        1005
#define IDC_NOW                         1005
#define IDC_ALARM                       1006
#define IDC_ERROR                       1008
#define IDC_SET                         1009
#define IDC_RESET                       1010
#define IDC_STATUS                      1011
#define IDC_VALUE                       1012
#define IDC_OUTPUT                      1013
#define IDC_LIMIT_MAX                   1014
#define IDC_LIMIT_MIN                   1015
#define IDC_DATE                        1024
#define IDC_LENGTH                      1026
#define IDC_RANK0                       1027
#define IDC_RANK2                       1029
#define IDC_RANK3                       1030
#define IDC_RANK4                       1031
#define IDC_RANK5                       1032
#define IDC_RANK6                       1033
#define IDC_RANK7                       1034
#define IDC_RANK8                       1035
#define IDC_RANK9                       1036
#define IDC_PWD                         1037
#define IDC_RANK10                      1037
#define IDC_NEW_PWD                     1038
#define IDC_CFM_PWD                     1040
#define IDC_NOSWITCH                    1043
#define IDC_SW2                         1046
#define IDC_TAG1                        1047
#define IDC_CA1                         1048
#define IDC_MIN1                        1049
#define IDC_MAX1                        1050
#define IDC_TAG2                        1051
#define IDC_CA2                         1052
#define IDC_MIN2                        1053
#define IDC_MAX2                        1054
#define IDC_TAG3                        1055
#define IDC_CA3                         1056
#define IDC_MIN3                        1057
#define IDC_MAX3                        1058
#define IDC_TAG4                        1059
#define IDC_CA4                         1060
#define IDC_MIN4                        1061
#define IDC_MAX4                        1062
#define IDC_TAG5                        1063
#define IDC_CA5                         1064
#define IDC_MIN5                        1065
#define IDC_MAX5                        1066
#define IDC_SAVE                        1067
#define IDC_LOAD                        1068
#define IDC_OBJECTS                     1070
#define IDC_LINKS                       1071
#define IDC_LOOPLIST                    1072
#define IDC_INTERVAL                    1075
#define IDC_CHECK1                      1076
#define IDC_TREND                       1077
#define IDC_AUTO_SCALE                  1078
#define IDC_DEL                         1079
#define IDC_EDIT1                       1081
#define IDC_USER_NAME                   1081
#define IDC_GROUP_NEWNAME               1081
#define IDC_GROUP_NAME                  1081
#define IDC_USER                        1081
#define IDC_FILTER                      1081
#define IDC_USER_PASSWORD               1082
#define IDC_USER_PASSWORD2              1083
#define IDC_CURRENTUSER                 1084
#define IDC_LOGIN                       1085
#define IDC_LOGOUT                      1086
#define IDC_USERMANAGER                 1087
#define IDC_USER_PASSWORDOLD            1093
#define IDC_USER_PASSWORDNEW            1094
#define IDC_USER_PASSWORDNEW2           1095
#define IDC_USERTREE                    1095
#define IDC_APPLY                       1096
#define IDC_USERRANK                    1097
#define IDC_ALARM_ACKED                 1099
#define IDC_ALARM_HIS                   1100
#define IDC_ALARM_QUERY                 1101
#define IDC_PRINT_BTN                   1102
#define IDC_OUTFILE_BTN                 1103
#define IDC_SOUND_ON                    1104
#define IDC_SOUND_ON2                   1105
#define IDC_SOUND_OFF                   1105
#define IDC_AckAlarmList                1106
#define IDC_LIST_HIS                    1107
#define IDC_LIST_ACKED                  1108
#define IDC_STATIC_ALARM_ACK            1109
#define IDC_CLOSEALARM                  1110
#define IDC_EVENT_TYPE                  1111
#define IDC_DATE_START                  1112
#define IDC_DATE_END                    1113
#define IDC_TIME_START                  1114
#define IDC_TIME_END                    1115
#define IDC_CHOOSE1                     1115
#define IDC_REFRESH                     1116
#define IDC_LISTKEYNAME                 1117
#define IDC_BUTTON1                     1123
#define IDC_CHOOSE2                     1124
#define IDC_CHOOSE3                     1125
#define IDC_ALARMTITLE                  1125
#define IDC_CHOOSE4                     1126
#define IDC_ALARM_REFRESH               1126
#define IDC_CHOOSE5                     1127
#define IDC_ALARM_BTN_R                 1127
#define IDC_ALARM_BTN_Y                 1128
#define IDC_ALARM_BTN_W                 1129
#define IDC_ALARM_BTN_G                 1130
#define IDC_LIST_REAL                   1131
#define IDC_CHECK_alarm_R               1132
#define IDC_CHECK_alarm_Y               1133
#define IDC_CHECK_alarm_W               1134
#define IDC_CHECK_alarm_G               1135
#define ID_ROOT_32771                   32771
#define ID_ROOT_32772                   32772
#define ID_GROUP_32773                  32773
#define ID_GROUP_32774                  32774
#define ID_GROUP_32775                  32775
#define ID_USER_32776                   32776
#define ID_USER_32777                   32777
#define ID_GROUP_NEW                    32778
#define ID_GROUP_DELETEALL              32779
#define ID_USER_NEW                     32780
#define ID_GROUP_EDIT                   32781
#define ID_USER_EDIT                    32782
#define ID_USER_DELETE                  32783
#define ID_GROUP_DELETE                 32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1134
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
