//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by hisq.rc
//
#define IDC_PEN1                        3
#define IDC_PEN2                        4
#define IDC_PEN3                        5
#define IDC_PEN4                        6
#define IDC_PEN5                        7
#define IDC_PEN6                        8
#define IDC_PEN7                        9
#define IDC_PEN8                        10
#define IDC_PEN9                        11
#define IDC_PEN10                       12
#define IDC_LOAD                        15
#define IDC_SAVE                        16
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MCHISQTYPE                  129
#define IDD_QUERY                       130
#define IDD_IP                          131
#define IDD_FORMAT                      132
#define IDD_FORMAT_CURVE                133
#define IDD_PRTCOUNT                    136
#define IDC_TAG1                        1001
#define IDC_TAG2                        1003
#define IDC_DIS1                        1004
#define IDC_TAG3                        1005
#define IDC_DIS2                        1006
#define IDC_TAG4                        1007
#define IDC_DIS3                        1008
#define IDC_TAG5                        1009
#define IDC_DIS4                        1010
#define IDC_TAG6                        1011
#define IDC_DIS5                        1012
#define IDC_TAG7                        1013
#define IDC_DIS6                        1014
#define IDC_TAG8                        1015
#define IDC_DIS7                        1016
#define IDC_TAG9                        1017
#define IDC_DIS8                        1018
#define IDC_TAG10                       1019
#define IDC_DATE_STA                    1020
#define IDC_TIME_STA                    1021
#define IDC_STEP                        1022
#define IDC_DIS9                        1022
#define IDC_COUNT                       1023
#define IDC_SERVERIP                    1023
#define IDC_DIS10                       1023
#define IDC_CURIP                       1024
#define IDC_DATE_END                    1024
#define IDC_EDIT_FORMAT                 1025
#define IDC_TIME_END                    1025
#define IDC_LIST_FORMAT                 1026
#define IDC_LENGTH                      1026
#define IDC_SHOW_GRID                   1027
#define IDC_HOR_GRID                    1028
#define IDC_VER_GRID                    1029
#define IDC_ZOOM_AUTO                   1030
#define IDC_SELTAG1                     1030
#define IDC_VER_WT1                     1030
#define IDC_MIN1                        1031
#define IDC_SELTAG2                     1031
#define IDC_MAX1                        1032
#define IDC_SELTAG3                     1032
#define IDC_CA1                         1033
#define IDC_SELTAG4                     1033
#define IDC_VER_WT2                     1033
#define IDC_CA2                         1034
#define IDC_FIRST_TAG                   1034
#define IDC_SELTAG5                     1034
#define IDC_VER_WT3                     1034
#define IDC_CA3                         1035
#define IDC_LAST_TAG                    1035
#define IDC_SELTAG6                     1035
#define IDC_VER_WT4                     1035
#define IDC_CA4                         1036
#define IDC_LINK                        1036
#define IDC_SELTAG7                     1036
#define IDC_VER_WT5                     1036
#define IDC_CA5                         1037
#define IDC_SELTAG8                     1037
#define IDC_VER_WT6                     1037
#define IDC_CA6                         1038
#define IDC_SELTAG9                     1038
#define IDC_VER_WT7                     1038
#define IDC_CA7                         1039
#define IDC_SELTAG10                    1039
#define IDC_VER_WT8                     1039
#define IDC_CA8                         1040
#define IDC_VER_WT9                     1040
#define IDC_CA9                         1041
#define IDC_VER_WT10                    1041
#define IDC_CA10                        1042
#define IDC_VER_WT11                    1042
#define IDC_MIN2                        1043
#define IDC_MAX2                        1044
#define IDC_MIN3                        1045
#define IDC_MAX3                        1046
#define IDC_MIN4                        1047
#define IDC_MAX4                        1048
#define IDC_MIN5                        1049
#define IDC_MAX5                        1050
#define IDC_MIN6                        1051
#define IDC_MAX6                        1052
#define IDC_MIN7                        1053
#define IDC_MAX7                        1054
#define IDC_MIN8                        1055
#define IDC_MAX8                        1056
#define IDC_MIN9                        1057
#define IDC_MAX9                        1058
#define IDC_MIN10                       1059
#define IDC_MAX10                       1060
#define ID_VIEW_CURVE                   32772
#define ID_OPT_QUERY                    32773
#define ID_OPT_PRINT                    32774
#define ID_MENUITEM32775                32775
#define ID_OPT_IP                       32776
#define ID_VIEW_FORMAT                  32777
#define ID_FORMAT_CURVE                 32778
#define ID_OPT_OUTFILE                  32779
#define ID_OPT_SCRPRV                   32780
#define ID_OPT_SRCLTR                   32781
#define ID_OPT_SCRLTR                   32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
