MODULE_TYPE=executable
MODULE_NAME=mkkey
FileDescription="PMC Authentication Utility"
SOURCES=mkkey.cpp ../d3des.c ../pmc_license.cpp ../hdid.cpp
NEED_LIBS=rtk utils
WIN32_LIBS=
include $(TOPDIR)/Rules.mk

